/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formTable;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class tb_pengadaanBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form tb_pengadaanBarang
     */
    siecoprint.tmpIp alamatIP = new siecoprint.tmpIp();
    
    public void setTable(JTable table, int row) {
        DefaultTableModel tablemodel = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null}
                },
                new String[]{
                    "ID Pengadaan", "ID Pegawai", "Nama Barang", "Tipe Barang", "Tanggal Permintan", "Banyak Barang", "Harga Satuan", "Total Anggaran", "Status"
                });
        table.setModel(tablemodel);
        String[] data = {null};

        for (int i = 0; i < row; i++) {
            ((DefaultTableModel) table.getModel()).addRow(data);
        }
    }

    public void id_pegawai() {
        try {
            //Connection con = koneksi.konek.koneksiDB();
            Statement st = koneksi_database.koneksi.koneksiDB(alamatIP.getIp()).createStatement();
            String sql = "select id_pegawai from tb_pegawai order by id_pegawai asc";
            ResultSet res = st.executeQuery(sql);
            while (res.next()) {
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                jCidPegawai.addItem(ob[0]);
            }
            res.close();
            st.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public tb_pengadaanBarang() {
        initComponents();
        //id_pegawai();
        jLStatus.setText("Waiting");

        jTjumlahBarang.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (jTjumlahBarang.getText().equals("") || jThargaSatuan.getText().equals("")) {
                    jLtotalharga.setText(String.valueOf("0"));
                    jLNoPB.setText("");
                } else {
                    int total = Integer.parseInt(jThargaSatuan.getText()) * Integer.parseInt(jTjumlahBarang.getText());
                    jLtotalharga.setText(String.valueOf(total));
                    Date tgl = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("ddmmyyyyhhmss");
                    String idNo = "PB" + sdf.format(tgl);
                    jLNoPB.setText(idNo);
                }

            }
        });

        jThargaSatuan.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (jTjumlahBarang.getText().equals("") || jThargaSatuan.getText().equals("")) {
                    jLtotalharga.setText(String.valueOf("0"));
                    jLNoPB.setText("");
                } else {
                    int total = Integer.parseInt(jThargaSatuan.getText()) * Integer.parseInt(jTjumlahBarang.getText());
                    jLtotalharga.setText(String.valueOf(total));
                    Date tgl = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("ddmmyyyyhhmss");
                    String idNo = "PB" + sdf.format(tgl);
                    jLNoPB.setText(idNo);
                }

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCidPegawai = new javax.swing.JComboBox();
        jTnamaBarang = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        jTjumlahBarang = new javax.swing.JTextField();
        jLStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTtipeBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jThargaSatuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLNoPB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelHasil = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLtotalharga = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pengadaan Barang"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("ID Pegawai");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Tanggal");

        jLabel5.setText("Jumlah Barang");

        jLabel6.setText("Status");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipe Barang");

        jLabel8.setText("Harga Satuan");

        jLabel4.setText("No Pengadaan Barang");

        jTabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabelHasil);

        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Total Harga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCidPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTnamaBarang)
                            .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jTtipeBarang))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTjumlahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jThargaSatuan)
                            .addComponent(jLStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtotalharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(jLNoPB, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCidPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTnamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTtipeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTjumlahBarang)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLNoPB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jThargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Vector tampungData = new Vector();
    Vector tampungKata = new Vector();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            tampungData.removeAllElements();
            for (int a = 0; a < jTabelHasil.getRowCount(); a++) {
                String sql = "insert into tb_pengadaanbarang values ('" + jTabelHasil.getValueAt(a, 0).toString() + "','" + jLNoPB.getText() + "','" + jTabelHasil.getValueAt(a, 1).toString() + "','" + jTabelHasil.getValueAt(a, 2).toString() + "','" + jTabelHasil.getValueAt(a, 3).toString() + "','" + jTabelHasil.getValueAt(a, 4).toString() + "','" + jTabelHasil.getValueAt(a, 5).toString() + "','" + jTabelHasil.getValueAt(a, 6).toString() + "','" + jTabelHasil.getValueAt(a, 7).toString() + "','" + jTabelHasil.getValueAt(a, 8).toString() + "')";
                java.sql.Connection conn = (java.sql.Connection) koneksi_database.koneksi.koneksiDB(alamatIP.getIp());
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
            }
            JOptionPane.showMessageDialog(rootPane, "Berhasil Menyimpan Transaksi");
            jTabelHasil.setModel(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal Menyimpan Transaksi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Date tanggal = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("MMM");
            SimpleDateFormat sd = new SimpleDateFormat("hhmmss");
            String id = sd.format(tanggal) + sdf.format(tanggal) + jTnamaBarang.getText().substring(0, 2) + jCidPegawai.getSelectedItem();
            SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = String.valueOf(form.format(jDate.getDate()));
            tampungKata.removeAllElements();
            tampungData.add(id + "\t" + jCidPegawai.getSelectedItem() + "\t" + jTnamaBarang.getText() + "\t" + jTtipeBarang.getText() + "\t" + tgl + "\t" + jTjumlahBarang.getText() + "\t" + jThargaSatuan.getText() + "\t" + jLtotalharga.getText() + "\t" + jLStatus.getText());
            for (int i = 0; i < tampungData.size(); i++) {
                String kata = tampungData.get(i).toString();
                String[] pKata = kata.split("\t");
                for (String tmp : pKata) {
                    tampungKata.add(tmp);
                }
            }

            setTable(jTabelHasil, jTabelHasil.getRowCount());
            for (int j = 0; j < tampungData.size(); j++) {
                int batas = j * 9;
                jTabelHasil.setValueAt(tampungKata.get(batas), j, 0);
                jTabelHasil.setValueAt(tampungKata.get(batas + 1), j, 1);
                jTabelHasil.setValueAt(tampungKata.get(batas + 2), j, 2);
                jTabelHasil.setValueAt(tampungKata.get(batas + 3), j, 3);
                jTabelHasil.setValueAt(tampungKata.get(batas + 4), j, 4);
                jTabelHasil.setValueAt(tampungKata.get(batas + 5), j, 5);
                jTabelHasil.setValueAt(tampungKata.get(batas + 6), j, 6);
                jTabelHasil.setValueAt(tampungKata.get(batas + 7), j, 7);
                jTabelHasil.setValueAt(tampungKata.get(batas + 8), j, 8);
            }
            JOptionPane.showMessageDialog(rootPane, "Berhasil Ditambahkan Kedalam keranjang");
            jCidPegawai.setSelectedIndex(0);
            jTtipeBarang.setText("");
            jTnamaBarang.setText("");
            jDate.setDate(null);
            jTjumlahBarang.setText("");
            jThargaSatuan.setText("");
            jLtotalharga.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal Menambahkan Kedalam Keranjang");
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCidPegawai;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLNoPB;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLtotalharga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelHasil;
    private javax.swing.JTextField jThargaSatuan;
    private javax.swing.JTextField jTjumlahBarang;
    private javax.swing.JTextField jTnamaBarang;
    private javax.swing.JTextField jTtipeBarang;
    // End of variables declaration//GEN-END:variables
}
